# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_fabricante', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('grupo', models.CharField(blank=True, max_length=200, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('garantia', models.CharField(blank=True, max_length=200, null=True)),
                ('clase', models.CharField(blank=True, max_length=200, null=True)),
                ('disponible', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.CharField(blank=True, max_length=200, null=True)),
                ('moneda', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_tecnica', models.CharField(blank=True, max_length=200, null=True)),
                ('ficha_comercial', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.URLField()),
                ('disponibleCD', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
