# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cva', '0003_auto_20160610_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='modena_descuento',
            new_name='moneda_descuento',
        ),
    ]
